language: node_js
node_js:
  - node
  - 7
  - 6
  - 5
  - 4

cache:
  directories:
    - "node_modules"

script:
  - which hexo
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: hexo.yihui.name
