language: node_js
node_js:
  - node

cache:
  directories:
    - "node_modules"

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  fqdn: hexo.yihui.name
